### ISSUE TITLE
Finish Milestone 2 Items

### ISSUE THREAD

**Issue by mikem2m** [UBC-MDS/DSCI522-2425-group24_adult-income-predictor#11]
- [x]  lock package versions in environment.yml
- [x]  create platform specific conda lock file
- [x]  dockerfile
- [x]  deploy docker to github action
- [x]  docker compose
- [x]  data validation
- [x]  readme changes

**Comment by mikem2m** [comment]
@fraramfra @Calista321 @QuanhuaHuang-ubc Please finish the data validation section as shown above. Thanks!
